---
title: "Analysis of New York Dogs"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(viridis)
library(leaflet)
lat_lon = read.csv("./data/lat-long.csv")
```

```{r, include=FALSE}
dogz = read.csv("./data/NYC_Dog_Licensing_Dataset.csv") %>% 
  janitor::clean_names() %>% 
  filter(breed_name != "Unknown",
         extract_year-animal_birth_month < 20) %>% 
  mutate(animal_name = str_to_sentence(animal_name),
         borough = ifelse(zip_code %in% c(10001:10282),"Manhattan", borough),
         borough = ifelse(zip_code %in% c(10301:10314), "Staten Island", borough),
         borough = ifelse(zip_code %in% c(10451:10475), "Bronx", borough),
         borough = ifelse(zip_code %in% c(11004,11101:11106,11109,11351,11354:11375,11377:11379,11385,11411:11423,11426:11430,11432:11436,11691:11694,11697), "Queens", borough),
         borough = ifelse(zip_code %in% c(11201,11203:11226,11228:11239,11241:11243,11249,11252,11256), "Brooklyn", borough),
         borough = as.factor(borough),
         breed_name = as.character(breed_name),
         license_issued_date = as.Date(license_issued_date, format = "%m/%d/%Y"),
         license_expired_date = as.Date(license_expired_date, format = "%m/%d/%Y"),
         license_length = year(license_expired_date) - year(license_issued_date),
         dog_age = 2019 - animal_birth_month,
         breed_name = ifelse(breed_name == "American Pit Bull Terrier/Pit Bull", "American Pit Bull Mix / Pit Bull Mix", breed_name),
         breed_name = ifelse(breed_name == "American Pit Bull Terrier/Pit Bull", "American Pit Bull Mix / Pit Bull Mix", breed_name),
         breed_name = ifelse(breed_name == "Australian Cattle Dog", "Australian Cattledog", breed_name),
         breed_name = ifelse(breed_name == "Bassett Hound", "Basset Hound", breed_name),
         breed_name = ifelse(breed_name == "Brittany", "Brittany Spaniel", breed_name),
         breed_name = ifelse(breed_name == "Coonhound, Black and Tan", "Black and Tan Coonhound", breed_name),
         breed_name = ifelse(breed_name == "Coonhound, Black and Tan", "Black and Tan Coonhound", breed_name),
         breed_name = ifelse(breed_name == "Coonhound, Blue Tick", "Bluetick Coonhound", breed_name),
         breed_name = ifelse(breed_name == "Coonhound, Treeing Walker", "Treeing Walker Coonhound", breed_name),
         breed_name = ifelse(breed_name == "Cotton de Tulear", "Coton de Tulear", breed_name),
         breed_name = ifelse(breed_name == "Japanese Chin/Spaniel", "Japanese Chin", breed_name),
         breed_name = ifelse(breed_name == "Jindo Dog, Korea", "Jindo", breed_name),
         breed_name = ifelse(breed_name == "Mastiff, French (Dogue de Bordeaux)", "Dogue de Bordeaux", breed_name),
         breed_name = ifelse(breed_name == "Pharoh hound", "Pharaoh Hound", breed_name),
         breed_name = ifelse(breed_name == "Schipperke", "Schipperkee", breed_name),
         breed_name = ifelse(breed_name == "Schnauzer, Miniature", "Miniature Schnauzer", breed_name),
         breed_name = ifelse(breed_name == "Schnauzer, Miniature Crossbreed", "Miniature Schnauzer, Crossbreed", breed_name),
         breed_name = ifelse(breed_name == "Welsh Corgi, Cardigan", "Cardigan Welsh Corgi", breed_name),
         breed_name = ifelse(breed_name == "Welsh Corgi, Pembroke", "Pembroke Welsh Corgi", breed_name),
         breed_name = ifelse(breed_name == "Bull Dog, French", "French Bulldog", breed_name),
         breed_name = ifelse(breed_name == "Collie, Bearded", "Bearded Collie", breed_name),
         breed_name = ifelse(breed_name == "Bullmastiff", "Mastiff, Bull", breed_name),
         breed_name = ifelse(breed_name == "Neapolitan Mastiff", "Mastiff, Neapolitan", breed_name),
         breed_name = ifelse(breed_name == "Tibetan Mastiff", "Mastiff, Tibetan", breed_name),
         breed_name = ifelse(breed_name == "Pointer, German Shorthaired", "German Shorthaired Pointer", breed_name),
         breed_name = ifelse(breed_name == "Pointer, German Wirehaired", "German Wirehaired Pointer", breed_name),
         breed_name = ifelse(breed_name == "Schnauzer, Giant", "Giant Schnauzer", breed_name),
         breed_name = ifelse(breed_name == "Schnauzer, Standard", "Standard Schnauzer", breed_name),
         breed_name = ifelse(breed_name == "Chinese Shar-Pei", "Shar-Pei, Chinese", breed_name)) %>% 
  drop_na(borough) %>% 
  rename(animal_birth_year = animal_birth_month, license_id = row_number) %>% 
  select(-extract_year)

```

```{r, include = FALSE}
dogz_1 =
  dogz %>% 
  distinct(animal_name, animal_gender, animal_birth_year, breed_name, .keep_all = TRUE) %>% 
  select (-license_issued_date, -license_expired_date, -license_length)

distinct_dogz =
  left_join(dogz_1, lat_lon, by = "zip_code") %>% 
  select(-City,-State,-Timezone,-Daylight.savings.time.flag,-geopoint) %>% 
  janitor::clean_names()
```

# Gender of dogs by borough 


```{r, echo=FALSE}
plot_2=
  distinct_dogz %>% 
  filter(animal_gender == "M" | animal_gender == "F") %>% 
  ggplot(aes(x = borough, fill = animal_gender)) +
  geom_histogram(position = "dodge", stat = "count") +
  labs(
    title = "Gender of dogs by borough",
    x = "New York Borough",
    y = "Dog Gender"
  )
plot_2
```


# Age distribution of dogs by boroughs 

```{r, echo=FALSE}
plot_3=
  ggplot(distinct_dogz, aes(x = borough, y = dog_age)) +
  geom_boxplot (color = "purple") +
  labs(
    title = "Age distribution of dogs by borough",
    x = "New York Borough",
    y = "Dog's Age"
  )
plot_3
```


# Breed of dogs by borough

```{r, echo=FALSE}
plot_4=
  distinct_dogz %>% 
  group_by(borough) %>% 
  count(breed_name) %>% 
  top_n(5) %>% 
  ggplot(aes(x = breed_name, y = n)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_grid(~borough) +
  labs(
    title = "Top 10 breeds of dogs by borough",
    x = "Dog Breed",
    y = "Total Count"
  )
plot_4
```

# License issue date 

```{r, echo=FALSE}
plot_5 =
dogz %>% 
group_by(license_issued_date) %>% 
  summarize(n_obs = n()) %>% 
    ggplot(aes(x = license_issued_date, y = n_obs, color = n_obs)) + 
    geom_point() +
    labs(title = "Number of licenses over time", 
    x = "License issue date", 
    y = "Number of licenses")
plot_5
```



```{r, echo=FALSE}
plot_5.5=
  dogz %>% 
  mutate(license_issued_date = floor_date(as_date(license_issued_date), "month")) %>% 
  group_by(license_issued_date) %>% 
  summarize(n_obs = n()) %>% 
      ggplot(aes(x = license_issued_date, y = n_obs, color = n_obs)) + 
      geom_point() + geom_line() +
      labs(title = "Number of licenses over time", 
      x = "License issue date", 
      y = "Number of licenses")
plot_5.5
```


```{r, echo=FALSE}
plot_5.51=
  dogz %>% 
  mutate(license_issued_date = month(license_issued_date),
         license_issued_date = month.abb[license_issued_date],
         license_issued_date = factor(license_issued_date, c("Jan","Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug", "Sep", "Oct","Nov", "Dec"), ordered = TRUE)) %>%
  group_by(license_issued_date) %>% 
  summarize(n_obs = n()) %>% 
      ggplot(aes(x = license_issued_date, y = n_obs)) + 
      geom_point() + geom_line(group=1) +
      labs(title = "Number of licenses issued per month", 
      x = "License issue date", 
      y = "Number of licenses")
plot_5.51
```


# Top name by birth year

```{r, echo=FALSE}
plot_6 = 
distinct_dogz %>% 
  filter(animal_name != "Unknown",
         animal_name != "Name not provided",
         animal_name != "Name",
         animal_birth_year != 1997) %>% 
  group_by(animal_birth_year, animal_name) %>% 
  summarize(n_obs = n()) %>% 
  top_n(1) %>% 
    ggplot(aes(x=animal_birth_year, y=n_obs, group = animal_name, color = animal_name)) + geom_point() + geom_line() +
  labs(title = "Top name by birth year", 
    x = "Birth year", 
    y = "Number of dogs")
plot_6
```


# Regression to predict the age of dog by borough, gener, and breed

```{r, include=FALSE}

#Regression analysis: predict the age of the dog (y) if you know the boro (x1) and gender (x2) and breed (x3)

#Step 0: Cleaning: change breed_name to a factor rather than a character varialbe
distinct_dogz_reg = 
  distinct_dogz %>% 
  mutate(
    breed_name = as.factor(breed_name)
  )
distinct_dogz_reg
```

```{r, include=FALSE}
#create reference groups that are coded as 
distinct_dogz_reg = 
  distinct_dogz_reg %>% 
  mutate(
    borough = fct_infreq(borough),
    animal_gender = fct_infreq(animal_gender),
    breed_name = fct_infreq(breed_name)
    )
#run linear regression with dog age as Y and borough, breed name and animal gender as categorical
fit = lm(dog_age ~ borough + animal_gender, data = distinct_dogz)

#view outputs
fit %>% 
  broom::tidy()

#create tidy table
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```

```{r, include=FALSE}
#model residuals 
modelr::add_residuals(distinct_dogz_reg, fit)
```

```{r, echo=FALSE}
#graph residuals for each borough
distinct_dogz_reg %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) + geom_violin()
```



